// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201104013122_Migracion2")]
    partial class Migracion2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("BlazorApp1.Data.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnName("Date")
                        .HasColumnType("datetime");

                    b.Property<Resource>("Resource")
                        .HasColumnName("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnName("ResourceId1")
                        .HasColumnType("INTEGER");

                    b.Property<Tasks>("Task")
                        .HasColumnName("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnName("TaskId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnName("time")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Detail");
                });

            modelBuilder.Entity("BlazorApp1.Data.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnName("UserId1")
                        .HasColumnType("INTEGER");

                    b.Property<User>("user")
                        .HasColumnName("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("BlazorApp1.Data.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estimate")
                        .HasColumnName("Estimate")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnName("Expiration")
                        .HasColumnType("datetime");

                    b.Property<Resource>("Resource")
                        .HasColumnName("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnName("ResourceId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnName("State")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .HasColumnName("Name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("BlazorApp1.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnName("Lastname")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasColumnName("Password")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
